### ISSUE TITLE
How to run Shiny interface for local RNA-seq analysis?

### ISSUE THREAD

**Issue by BenAawf** [giuliospinozzi/arpir#1]
Hi, dear developer, 
First of all, thank you for such exciting work; I find it very helpful.
Kindly, I would like to ask you for a bit of help if you can make a video that explains how I can run the shiny graphical interface to perform Local analysis.
Best regards
BenAawf

**Comment by giuliospinozzi** [comment]
Is not in plan a video tutorial as in SiCoDEA. You can refer to https://github.com/giuliospinozzi/arpir/blob/master/shiny.md

Best
